# Generated by Django 5.1.1 on 2024-09-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_archive', models.BooleanField(default=False, verbose_name='Архивировано ли')),
                ('preview_image', models.ImageField(upload_to='arts/preview/', verbose_name='Изображение превью')),
                ('state', models.CharField(blank=True, choices=[('BUF', 'Закрашенно'), ('NEW', 'В процессе')], max_length=3, null=True, verbose_name='Состояния художества')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Художество',
                'verbose_name_plural': 'Художества',
            },
        ),
        migrations.CreateModel(
            name='ArtComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('is_moderate', models.BooleanField(verbose_name='Прошел ли модерацию')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Коментарий',
                'verbose_name_plural': 'Коментарии',
            },
        ),
        migrations.CreateModel(
            name='ArtCoords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long', models.FloatField(verbose_name='Широта')),
                ('lant', models.FloatField(verbose_name='Долгота')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Координаты художества',
                'verbose_name_plural': 'Координаты художества',
            },
        ),
        migrations.CreateModel(
            name='ArtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='arts/preview/', verbose_name='Координаты')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Изображение художества',
                'verbose_name_plural': 'Изображения художеств',
            },
        ),
    ]
