# Generated by Django 5.1.1 on 2024-09-17 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='artcomment',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts.art', verbose_name='Художество'),
        ),
        migrations.AddField(
            model_name='artcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='art',
            name='coords',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arts.artcoords', verbose_name='Координаты'),
        ),
        migrations.AddField(
            model_name='artimage',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts.art', verbose_name='Художество'),
        ),
    ]
